### ISSUE TITLE
Specification is too tied to enterprise/admin use cases

### ISSUE THREAD

**Issue by mgiuca** [screen-share/capture-all-screens#21]
Reading through the spec, I was struck by this particular paragraph (emphasis mine):

> The user agent MUST obtain permission by checking an allowlist of origins **specified by an administrator or device owner**. If the origin is not in the **allowlist defined by the administrator**, reject p with a new DOMException object whose name attribute has the value NotAllowedError and return p.

This is the first (and last) time a device administrator is mentioned in the spec, so for one thing, if that's the only intended mode, then it should be explained up front as such ("this is an API to allow administrators to grant websites access to all screens"). But this seems a little weird to me, from a platform perspective, to have `getDisplayMedia` be a general web API that lets users grant access to a selected display, and `getAllScreensMedia` be essentially the same concept only it picks all displays at once, but it only works when administrators explicitly allowlist the origin.

In my opinion, `getAllScreensMedia` should be available on all origins to all users, and should basically have the same permission model as `getDisplayMedia` only allowing multiple displays to be selected instead of one. This logically suggests that the dialog should be a multi-select where you pick which displays to return (similar to how you can show a file picker that only allows one file, or that allows multiple files to be picked).

I see in your [Alternatives Considered](https://github.com/screen-share/capture-all-screens/#alternatives-considered) section, you mention w3c/mediacapture-screen-share-extensions#8 in which @eladalon1983 proposes the same conclusion as I came to above. It says "This approach was abandoned due to insufficient Web-developer interest in the former without the latter." (But the thread looks like there was some positive responses?) I think going with that approach would make the web API side pretty straightforward, as it has exactly the same security story as getDisplayMedia, it only has a bit of new UX and API surface.

Now clearly there's an overriding use case to allow administrators to allowlist certain origins and give them access to the displays without prompting. I see that as a private agreement at the user agent level (not part of the spec), similar to how administrators in browsers can auto-grant certain permissions. So I would suggest that we don't make admin allowlisting a requirement of the spec, but rather a power that user agents can implicitly grant to administrators.

**Comment by eladalon1983** [comment]
> In my opinion, getAllScreensMedia should be available on all origins to all users, and should basically have the same permission model as getDisplayMedia only allowing multiple displays to be selected instead of one.

One of the key concerns with screen-sharing is around prompts - whether the user understands what they're doing and what implications there are, or whether the user is just trying to click away annoying prompts and get back to business. With the working assumption that gDM - the established API with some robust implementations - works well enough, it could be argued that [gDMS](https://github.com/w3c/mediacapture-screen-share-extensions/issues/8) is even more robust against careless permission-granting, as it requires more deliberate user interaction. (But it's open to debate.)

In contrast go gDM and gDMS, which ask a multiple-choice question, gASM asks a yes/no question, and such dialogs have been deemed to liable for careless permission-granting. There are some options which can close the gap - a policy, exposing the API only to extensions, "marine life"[*], etc. But simply exposing the functionality to any arbitrary origin is not something that'd pass privacy+security muster.

---
[*] Ping me internally.

**Comment by mgiuca** [comment]
I think it helps to decouple the API design (what is written in the spec) from the exposure policy (under what circumstances the API is available). The spec should not be concerned with the rules of when the API is exposed, although it can mention any security & privacy considerations.

Once you make that mental break between the spec and the implementation, you can see that all the points about:

- it only being exposed to enterprise devices,
- whether there's a picker or a simple permission prompt,
- whether or not admins should be able to override the picker and auto-grant it to certain origins,
- whether the API should be exposed in a restricted environment (like [IWAs](https://github.com/WICG/isolated-web-apps/blob/main/README.md)) only,

are implementation details that don't apply to the spec.

So my argument is that while we can mention all of the above in the spec, they shouldn't be part of the normative text (i.e. the algorithms described). They are up to the browser.

This also has bearing on the interface design as a whole. Once you remove the idea that we always expose all screens (and instead specify that the user agent should let the user decide -- possibly admin-overridable), then the API starts to look a lot like gDMS again - it's basically the same API as gDM except returning multiple media streams. So I would argue its design should reflect that it is a companion to gDM (for example, to be called `getDisplayMediaSet`).

**Comment by eladalon1983** [comment]
> The spec should not be concerned with the rules of when the API is exposed, although it can mention any security & privacy considerations.

There are precedents, e.g. exposing APIs only to [secure contexts](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts) or only if there's [cross-origin isolation](https://developer.mozilla.org/en-US/docs/Web/API/crossOriginIsolated).

> it only being exposed to enterprise devices,
> ...
> are implementation details that don't apply to the spec.

I think certain functionality is too dangerous to expose to anything but devices expressly configured to allow that functionality.

> they shouldn't be part of the normative text

It would indeed make sense to employ normative text that would not mention enterprise policies literally, but will effectively mean such policies or an equivalent.

> Once you remove the idea that we always expose all screens (and instead specify that the user agent should let the user decide -- possibly admin-overridable), then the API starts to look a lot like gDMS again

The original plan was indeed to ship gDMS and a policy-override. The pivot to gASM came after some thought and internal deliberation, and it'd help to understand this background when deciding how to move forward.

**Comment by shangl** [comment]
Closing this thread due to inactivity.
