### ISSUE TITLE
Is this on-track?

### ISSUE THREAD

**Issue by nsharma1396** [screen-share/capture-all-screens#23]
Hello,

This is a highly useful API for the agent screen capture use case and I wanted to understand if this is on track for shipping and when is it expected to be shipped. I noticed that it is available under a chrome flag until chrome 130 so is it planned to ship after that?

Apologies if I am missing out on something basic here, I am quite new to Chrome feature releases and hence not aware of it properly.

Thanks,
Neeraj

**Comment by shangl** [comment]
Hi Neeraj,

yes, we plan to ship this API. I can't share any details on the plans right now, but I recommend you to follow the [Chrome status](https://chromestatus.com/feature/6284029979525120) entry for this API over the next couple of months.

Best,
Simon

**Comment by nsharma1396** [comment]
Hi @shangl 

Appreciate the response and eagerly looking forward to seeing this shipped!

However, I noticed in the [Chrome status](https://chromestatus.com/feature/6284029979525120) entry that the origin trial is being extended for the following reason:

> Experiment Extension Reason
This API will eventually be released for isolated contexts, which are delayed. Hence, we are asking for an extension of the origin trial.

So, will this API be exclusively available in isolated-app:// applications context only (which makes it completely dependent on the successful release of isolated web apps), or will it be shipped in the browser environment as well?

Some clarity regarding where this API will surface will be extremely helpful

Thanks,
Neeraj

**Comment by shangl** [comment]
Hi @nsharma1396 ,

yes, this API is not planned outside of the `isolated-app://` context.

Best,
Simon
