### ISSUE TITLE
Snapshots and short-lived indicators

### ISSUE THREAD

**Issue by eladalon1983** [screen-share/capture-all-screens#4]
The spec discusses user-facing indicators that a capture is ongoing. However, if an app uses the API to grab snapshots every N seconds, the indicators might appear for such a brief time that the user misses them. The way iOS and Android tackle this risk is by ensuring that user-facing indicators are only disappear after K seconds. I think it would be good for this spec to make similar requirements, or at least recommendations.

**Comment by shangl** [comment]
Thanks. A requirement of keeping the usage indicator around for at least 5 seconds was added to the spec.
