### ISSUE TITLE
Did this migrate?

### ISSUE THREAD

**Issue by marcoscaceres** [screen-share/capture-all-screens#8]
Hi @shangl, according to [this email](https://lists.w3.org/Archives/Public/public-wicg/2023Feb/0002.html), this was migrated to https://github.com/screen-share/capture-all-screens ... is that correct? 

If so, it ok to archive this and point people to that repo instead? should we maybe delete this repo entirely as it appears the other one is a copy of this one?

**Comment by eladalon1983** [comment]
Hi @marcoscaceres. The current location - this repo - is the current intended location of the repo. Was this issue originally filed before the repo had moved, perhaps?

**Comment by shangl** [comment]
@marcoscaceres , what @eladalon1983 writes is correct. i also responded here [1] right now.

[1] https://github.com/WICG/multicapture/issues/7
